# Site setings
name: 'With Husky'
description: 'A year abroad with my dog — lessons learned and moments experienced.'
meta_description: 'Meta description goes here.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
? baseurl
production_url: https://withhusky.com
disqus: 'withhusky'
cover_image: bc_1.jpg

# Author
author:
  name: 'Caro'
  image: 'authorimage.jpg'
  greetings: '...with husky'
  description: 'A year abroad with my dog — lessons learned and moments experienced.'
  bio: 'Canadian living it up as a remote worker in France with husky — 3 year old, husky-lab-mutt-female.'

# Social links
twitter: 'withhusky'
instagram:
  'withhusky'
  # Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
