# Site setings
name: 'With Husky'
description: 'Travel with le petit loup.'
meta_description: 'Meta description goes here.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
? baseurl
production_url: https://withhusky.com
disqus: 'withhusky'
cover_image: bc_1.jpg

# Author
author:
  name: 'Caro'
  image: 'authorimage.jpg'
  greetings: '...with husky'
  description: 'This is a description about the blog. This is a description about the blog. This is a description about the blog.'
  bio: 'This is the bio. It goes on the about page. This is the bio. It goes on the about page. This is the bio. It goes on the about page.'

# Social links
twitter: 'withhusky'
instagram: 'withhusky'

navigation:
  - text: About
    url: /about

  # Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
